CREATE USER name_user WITH PASSWORD 'Password';
CREATE DATABASE name OWNER name_user;
GRANT ALL PRIVILEGES ON DATABASE name TO name_user;
\c name
GRANT ALL ON SCHEMA public TO name_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO name_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO name_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO name_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO name_user;